#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
One-command art fetcher.
Use --artist "Name" to automatically pull open images from:
Commons → Europeana → MET → CMA → AIC → Rijksmuseum,
dedupe results, and store them under Art/<LastName or Unknown>/UID__...

You can still use the manual mode: --source met/aic/cma/rijks/commons/europeana
"""
import os, re, csv, time, argparse
from pathlib import Path
from urllib.parse import urlencode
import requests
from requests.exceptions import RequestException
from tqdm import tqdm

# === paths ===
DEFAULT_IMAGES_ROOT = "/Users/tim/NoteDeck/MainDeck-modular/Library/Images"
def resolve_images_root(cli_root: str|None) -> Path:
    if cli_root: return Path(cli_root).expanduser().resolve()
    env = os.environ.get("ART_IMAGES_ROOT")
    return Path(env).expanduser().resolve() if env else Path(DEFAULT_IMAGES_ROOT).expanduser().resolve()

HEADERS = {"User-Agent": "NoteDeck-ArtFetcher/2.0 (local)"}

def slug(s: str) -> str:
    if s is None: s = ""
    repl = {"ä":"ae","ö":"oe","ü":"ue","ß":"ss","Ä":"Ae","Ö":"Oe","Ü":"Ue"}
    for k,v in repl.items(): s = s.replace(k,v)
    s = re.sub(r"\s+", " ", s).strip()
    s = re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_")
    return s or "untitled"

def norm(s: str) -> str:
    return slug(str(s)).lower()

def html_strip(x: str) -> str:
    return re.sub(r"<.*?>", "", x or "").strip()

# --- artist → folder (always LastName or Unknown) ---
def artist_folder(artist: str) -> str:
    if not artist: return "Unknown"
    a = artist.split(";")[0]
    a = re.sub(r"\(.*?\)", "", a)
    a = re.sub(r"\b\d{3,4}\s*[–-]\s*\d{2,4}\b", "", a)
    a = a.strip()
    if a.lower() in {"unknown","anonymous","unidentified","unknown maker",""}:
        return "Unknown"
    if "," in a:
        last = a.split(",")[0].strip()
    else:
        parts = a.split()
        last = parts[-1] if parts else "Unknown"
    return slug(last) or "Unknown"

def ensure_index(csv_path: Path):
    if not csv_path.exists():
        with csv_path.open("w", newline="", encoding="utf-8") as f:
            csv.DictWriter(f, fieldnames=[
                "uid","filename","artist","title","year","source","license","movement","keywords"
            ]).writeheader()

def read_rows(csv_path: Path):
    ensure_index(csv_path)
    with csv_path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def next_uid(rows):
    mx = 0
    for r in rows:
        m = re.match(r"ART(\d+)$", r.get("uid",""))
        if m: mx = max(mx, int(m.group(1)))
    return f"ART{mx+1:04d}"

def write_rows(csv_path: Path, rows):
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=[
            "uid","filename","artist","title","year","source","license","movement","keywords"
        ])
        w.writeheader(); w.writerows(rows)

def regenerate_tex(tex_path: Path, rows):
    def esc(s): 
        return (s or "").replace("\\","\\textbackslash{}").replace("{","\\{").replace("}","\\}")
    lines = ["% Auto-generated by art_fetch.py — DO NOT EDIT.", ""]
    uids = []
    for r in rows:
        uid = r["uid"]; uids.append(uid)
        cap = f'{r["artist"]}, {r["title"]} ({r["year"]})' if r["year"] else f'{r["artist"]}, {r["title"]}'
        lines += [
          fr"\providecommand{{\artpath@{uid}}}{{{esc(r['filename'])}}}",
          fr"\providecommand{{\artcap@{uid}}}{{{esc(cap)}}}",
          ""
        ]
    lines.append(r"\def\AllArtUIDs{" + ",".join(uids) + "}")
    tex_path.write_text("\n".join(lines), encoding="utf-8")

def unique_path(p: Path) -> Path:
    if not p.exists(): return p
    i, q = 2, p
    while q.exists():
        q = p.with_name(p.stem + f"-{i}" + p.suffix); i += 1
    return q

def make_sig(artist: str, title: str, year: str):
    return (norm(artist), norm(title), norm(year))

def load_seen(csv_path: Path):
    rows = read_rows(csv_path)
    return { make_sig(r["artist"], r["title"], r["year"]) for r in rows }

def save_image(url: str, artist: str, title: str, year: str, uid: str,
               art_dir: Path, images_root: Path) -> str:
    ext = ".jpg"
    m = re.search(r"\.(jpg|jpeg|png|tif|tiff)(?:$|\?)", url, re.I)
    if m: ext = "." + m.group(1).lower().replace("jpeg","jpg").replace("tiff","tif")

    folder = art_dir / artist_folder(artist)
    folder.mkdir(parents=True, exist_ok=True)

    year_clean   = slug(str(year)) if year else ""
    title_clean  = slug(title)[:90]
    artist_clean = slug(artist)[:60]

    fn = f"{uid}__{artist_clean}__{title_clean}{('__'+year_clean) if year_clean else ''}{ext}"
    path = unique_path(folder / fn)

    try:
        with requests.get(url, headers=HEADERS, stream=True, timeout=60) as r:
            r.raise_for_status()
            with open(path, "wb") as f:
                for chunk in r.iter_content(8192):
                    f.write(chunk)
    except RequestException as e:
        print(f"[warn] download failed for {url}: {e}")
        return ""
    return path.relative_to(images_root).as_posix()

def append_item(csv_path: Path, tex_path: Path, artist, title, year, relpath, uid, source, license_, movement="", keywords=""):
    rows = read_rows(csv_path)
    rows.append({
        "uid": uid, "filename": relpath,
        "artist": artist or "", "title": title or "", "year": str(year or ""),
        "source": source, "license": license_, "movement": movement, "keywords": keywords
    })
    write_rows(csv_path, rows); regenerate_tex(tex_path, rows)

# ========= Sources =========
def fetch_met(limit, y0, y1, query, art_dir, images_root, csv_path, tex_path, loose: bool, seen, dedupe: bool, artist_filter: str):
    base = "https://collectionapi.metmuseum.org/public/collection/v1"
    params = {"isPublicDomain":"true","hasImages":"true","dateBegin":y0,"dateEnd":y1,"q":query or "painting"}
    try:
        s = requests.get(f"{base}/search", params=params, headers=HEADERS, timeout=60).json()
    except Exception as e:
        print("[warn] MET search failed:", e); return
    ids = (s.get("objectIDs") or [])[:limit]
    for oid in tqdm(ids, desc="MET objects", unit="obj"):
        try:
            obj = requests.get(f"{base}/objects/{oid}", headers=HEADERS, timeout=60).json()
        except Exception:
            continue  # skip flaky objects
        if not obj.get("isPublicDomain"): continue
        img = obj.get("primaryImage") or obj.get("primaryImageSmall")
        if not img: continue
        if not loose:
            if not (("Paint" in (obj.get("classification") or "")) or
                    ("Paint" in (obj.get("objectName") or "")) or
                    ("oil" in (obj.get("medium") or "").lower())):
                continue
        artist = obj.get("artistDisplayName") or "Unknown"
        if artist_filter and artist_filter.lower() not in (artist or "").lower():
            continue
        title  = obj.get("title") or "Untitled"
        year   = obj.get("objectEndDate") or obj.get("objectBeginDate") or ""
        sig = make_sig(artist, title, year)
        if dedupe and sig in seen: 
            continue
        uid = next_uid(read_rows(csv_path))
        rel = save_image(img, artist, title, year, uid, art_dir, images_root)
        if rel:
            append_item(csv_path, tex_path, artist, title, year, rel, uid, "MET", "CC0")
            seen.add(sig)
            time.sleep(0.25)

def fetch_aic(limit, y0, y1, query, art_dir, images_root, csv_path, tex_path, seen, dedupe: bool, artist_filter: str):
    collected, page = 0, 1
    while collected < limit:
        params = {"page":page,"limit":50,
                  "fields":"id,title,artist_title,date_start,date_end,image_id,is_public_domain,artwork_type_title",
                  "query[term][is_public_domain]":"true"}
        if query: params["q"] = query
        if y0 is not None: params["query[range][date_start][gte]"] = y0
        if y1 is not None: params["query[range][date_end][lte]"] = y1
        try:
            r = requests.get("https://api.artic.edu/api/v1/artworks/search", params=params, headers=HEADERS, timeout=60).json()
        except Exception as e:
            print("[warn] AIC page failed:", e); break
        data = r.get("data", [])
        if not data: break
        for it in data:
            if collected >= limit: break
            if not it.get("is_public_domain"): continue
            if "painting" not in (it.get("artwork_type_title") or "").lower(): continue
            img_id = it.get("image_id")
            if not img_id: continue
            img = f"https://www.artic.edu/iiif/2/{img_id}/full/843,/0/default.jpg"
            artist = it.get("artist_title") or "Unknown"
            if artist_filter and artist_filter.lower() not in (artist or "").lower():
                continue
            title  = it.get("title") or "Untitled"
            year   = it.get("date_end") or it.get("date_start") or ""
            sig = make_sig(artist, title, year)
            if dedupe and sig in seen:
                continue
            uid = next_uid(read_rows(csv_path))
            rel = save_image(img, artist, title, year, uid, art_dir, images_root)
            if rel:
                append_item(csv_path, tex_path, artist, title, year, rel, uid, "AIC", "Public Domain")
                seen.add(sig)
                collected += 1
                time.sleep(1.0)  # polite
        page += 1

def fetch_cma(limit, y0, y1, query, art_dir, images_root, csv_path, tex_path, seen, dedupe: bool, artist_filter: str):
    params = {"cc0":"","has_image":1,"type":"Painting","limit":min(limit,1000)}
    if y0 is not None: params["created_after"] = y0
    if y1 is not None: params["created_before"] = y1
    if query: params["q"] = query
    url = "https://openaccess-api.clevelandart.org/api/artworks/?" + urlencode(params, doseq=True)
    try:
        r = requests.get(url, headers=HEADERS, timeout=60).json()
    except Exception as e:
        print("[warn] CMA search failed:", e); return
    data = r.get("data", [])
    for it in tqdm(data[:limit], desc="CMA objects", unit="obj"):
        img = None
        if it.get("images"):
            img = (it["images"].get("web") or {}).get("url") or (it["images"].get("print") or {}).get("url")
        if not img: continue
        artist = (it.get("creators") or [{}])[0].get("description") or it.get("creator") or it.get("tombstone", "") or "Unknown"
        if re.search(r"unknown|anonymous|unidentified", artist, re.I): artist = "Unknown"
        if artist_filter and artist_filter.lower() not in (artist or "").lower():
            continue
        title  = it.get("title") or "Untitled"
        year   = it.get("creation_date") or it.get("date_text") or ""
        sig = make_sig(artist, title, year)
        if dedupe and sig in seen:
            continue
        uid = next_uid(read_rows(csv_path))
        rel = save_image(img, artist, title, year, uid, art_dir, images_root)
        if rel:
            append_item(csv_path, tex_path, artist, title, year, rel, uid, "CMA", "CC0")
            seen.add(sig)
            time.sleep(0.25)

def fetch_rijks(limit, y0, y1, query, art_dir, images_root, csv_path, tex_path, api_key: str, seen, dedupe: bool, artist_filter: str):
    if not api_key:
        print("RIJKS API key fehlt: --rijks-key oder env RIJKS_API_KEY"); return
    collected, page, ps = 0, 1, 100
    base = "https://www.rijksmuseum.nl/api/en/collection"
    while collected < limit:
        params = {"key": api_key, "format": "json", "imgonly": "true", "ps": ps, "p": page, "type": "painting"}
        if query: params["q"] = query
        try:
            r = requests.get(base, params=params, headers=HEADERS, timeout=60).json()
        except Exception as e:
            print("[warn] Rijks page failed:", e); break
        objs = r.get("artObjects", [])
        if not objs: break
        for ob in objs:
            if collected >= limit: break
            img = (ob.get("webImage") or {}).get("url")
            if not img: continue
            artist = ob.get("principalMaker") or "Unknown"
            if artist_filter and artist_filter.lower() not in (artist or "").lower():
                continue
            title  = ob.get("title") or "Untitled"
            year   = ""
            sig = make_sig(artist, title, year)
            if dedupe and sig in seen:
                continue
            uid = next_uid(read_rows(csv_path))
            rel = save_image(img, artist, title, year, uid, art_dir, images_root)
            if rel:
                append_item(csv_path, tex_path, artist, title, year, rel, uid, "RIJKSMUSEUM", "see site")
                seen.add(sig)
                collected += 1
                time.sleep(0.25)
        page += 1

def fetch_commons(limit, query, art_dir, images_root, csv_path, tex_path, seen, dedupe, artist_filter, force_artist=""):
    """
    Rekursiv durch eine Commons-Kategorie inkl. Subkategorien laufen und Dateien holen.
    - query: "Category:…"; wenn leer -> "Category:Works by Wassily Kandinsky"
    - force_artist: überschreibt fehlende/unklare Metadaten (z.B. "Wassily Kandinsky")
    """
    base = "https://commons.wikimedia.org/w/api.php"
    start_cat = (query or "").strip()
    if not start_cat.lower().startswith("category:"):
        start_cat = f"Category:{start_cat}" if start_cat else "Category:Works by Wassily Kandinsky"

    allowed = ("public domain","cc","cc0","cc-by","cc-by-sa","pdm")
    collected = 0
    visited = set()
    queue = [start_cat]

    def fetch_files_from_category(cat):
        """liefert iterator über Dateiseiten mit imageinfo+extmetadata (mit paging)"""
        cont = None
        while True:
            params = {
                "action":"query","format":"json","formatversion":2,
                "generator":"categorymembers","gcmtitle":cat,
                "gcmnamespace":6,"gcmtype":"file","gcmlimit":50,
                "prop":"imageinfo|extmetadata","iiprop":"url|mime|size","iiurlwidth":4096
            }
            if cont: params["gcmcontinue"] = cont
            r = requests.get(base, params=params, headers=HEADERS, timeout=60).json()
            pages = (r.get("query") or {}).get("pages") or []
            for p in pages: yield p
            cont = (r.get("continue") or {}).get("gcmcontinue")
            if not cont: break

    def enqueue_subcats(cat):
        """fügt Subkategorien zur queue hinzu (mit paging)"""
        cont = None
        while True:
            params = {
                "action":"query","format":"json","formatversion":2,
                "list":"categorymembers","cmtitle":cat,
                "cmnamespace":14,"cmtype":"subcat","cmlimit":200
            }
            if cont: params["cmcontinue"] = cont
            r = requests.get(base, params=params, headers=HEADERS, timeout=60).json()
            cms = (r.get("query") or {}).get("categorymembers") or []
            for it in cms:
                sub = it.get("title")
                if sub and sub not in visited:
                    queue.append(sub)
            cont = (r.get("continue") or {}).get("cmcontinue")
            if not cont: break

    while queue and collected < limit:
        cat = queue.pop(0)
        if cat in visited: 
            continue
        visited.add(cat)

        # erst Dateien aus dieser Kategorie holen
        for p in fetch_files_from_category(cat):
            if collected >= limit: break
            ii = (p.get("imageinfo") or [{}])[0]
            url = ii.get("url")
            if not url: 
                continue
            meta = ii.get("extmetadata") or {}
            lic  = (meta.get("LicenseShortName",{}).get("value","") or "").lower()
            if not any(k in lic for k in allowed):
                continue

            artist = html_strip(meta.get("Artist",{}).get("value","")) or "Unknown"
            # Force-Artist hat Priorität; sonst aus der Kategorie ableiten
            if force_artist:
                artist = force_artist
            else:
                ql = start_cat.lower()
                if "kandinsky" in ql and "kandinsky" not in artist.lower():
                    artist = "Wassily Kandinsky"

            if artist_filter and artist_filter.lower() not in (artist or "").lower():
                continue

            title = html_strip(meta.get("ObjectName",{}).get("value","")) or p.get("title","").replace("File:","")
            year  = html_strip(meta.get("Date",{}).get("value",""))

            sig = make_sig(artist, title, year)
            if dedupe and sig in seen:
                continue

            uid = next_uid(read_rows(csv_path))
            rel = save_image(url, artist, title, year, uid, art_dir, images_root)
            if rel:
                append_item(csv_path, tex_path, artist, title, year, rel, uid, "COMMONS", lic or "PD/CC")
                seen.add(sig)
                collected += 1
                time.sleep(0.15)
        if collected >= limit:
            break

        # dann Subkategorien einreihen
        enqueue_subcats(cat)


def fetch_europeana(limit, query, art_dir, images_root, csv_path, tex_path, api_key: str, seen, dedupe, artist_filter):
    if not api_key:
        print("EUROPEANA API key fehlt: --europeana-key oder env EUROPEANA_API_KEY"); return
    base = "https://api.europeana.eu/record/v2/search.json"
    rows = 100; start = 1; collected = 0
    while collected < limit:
        params = {
            "wskey": api_key,
            "query": query or "",
            "qf": ["TYPE:IMAGE"],
            "reusability": "open",
            "media": "true",
            "profile": "rich",
            "rows": rows,
            "start": start
        }
        try:
            r = requests.get(base, params=params, headers=HEADERS, timeout=60).json()
        except Exception as e:
            print("[warn] Europeana page failed:", e); break
        items = r.get("items") or []
        if not items: break
        for it in items:
            if collected >= limit: break
            title = (it.get("title") or ["Untitled"])[0]
            img = (it.get("edmIsShownBy") or [None])[0] or (it.get("edmPreview") or [None])[0]
            if not img: continue
            artist = (it.get("dcCreator") or ["Unknown"])[0]
            if artist_filter and artist_filter.lower() not in (artist or "").lower():
                continue
            year = (it.get("year") or [""])[0] if isinstance(it.get("year"), list) else (it.get("year") or "")
            sig = make_sig(artist, title, year)
            if dedupe and sig in seen:
                continue
            uid = next_uid(read_rows(csv_path))
            rel = save_image(img, artist, title, year, uid, art_dir, images_root)
            if rel:
                append_item(csv_path, tex_path, artist, title, year, rel, uid, "EUROPEANA", "open (PDM/CC*)")
                seen.add(sig); collected += 1
                time.sleep(0.25)
        start += rows

# === SMART ARTIST MODE ===
def smart_fetch_artist(artist: str, sources: list[str], total_limit: int, per_source_limit: int,
                       y0: int, y1: int, art_dir: Path, images_root: Path, csv_path: Path, tex_path: Path,
                       rijks_key: str, europeana_key: str):
    print(f"Smart mode for artist: {artist}")
    seen = load_seen(csv_path)
    dedupe = True
    remaining = total_limit

    def take(n): 
        nonlocal remaining
        k = max(0, min(n, remaining))
        remaining -= k
        return k

    # Commons first (cheap & many)
    if "commons" in sources and remaining > 0:
        cats = [
            f"Category:Paintings by {artist}",
            f"Category:Watercolors by {artist}",
            f"Category:Drawings by {artist}",
            f"Category:Prints by {artist}",
            f"Category:Works by {artist}",
        ]
        for cat in cats:
            lim = take(per_source_limit if remaining > per_source_limit else remaining)
            if lim <= 0: break
            try:
                fetch_commons(lim, cat, art_dir, images_root, csv_path, tex_path, seen, dedupe, artist, force_artist=artist)
            except Exception as e:
                print("[warn] commons failed:", e)

    # Europeana
    if "europeana" in sources and remaining > 0:
        lim = take(per_source_limit if remaining > per_source_limit else remaining)
        try:
            fetch_europeana(lim, artist, art_dir, images_root, csv_path, tex_path, europeana_key, seen, dedupe, artist)
        except Exception as e:
            print("[warn] europeana failed:", e)

    # MET
    if "met" in sources and remaining > 0:
        lim = take(per_source_limit if remaining > per_source_limit else remaining)
        try:
            fetch_met(lim, y0, y1, artist, art_dir, images_root, csv_path, tex_path, True, seen, dedupe, artist)
        except Exception as e:
            print("[warn] met failed:", e)

    # CMA
    if "cma" in sources and remaining > 0:
        lim = take(per_source_limit if remaining > per_source_limit else remaining)
        try:
            fetch_cma(lim, y0, y1, artist, art_dir, images_root, csv_path, tex_path, seen, dedupe, artist)
        except Exception as e:
            print("[warn] cma failed:", e)

    # AIC
    if "aic" in sources and remaining > 0:
        lim = take(per_source_limit if remaining > per_source_limit else remaining)
        try:
            fetch_aic(lim, y0, y1, artist, art_dir, images_root, csv_path, tex_path, seen, dedupe, artist)
        except Exception as e:
            print("[warn] aic failed:", e)

    # Rijks
    if "rijks" in sources and remaining > 0:
        lim = take(per_source_limit if remaining > per_source_limit else remaining)
        try:
            fetch_rijks(lim, y0, y1, artist, art_dir, images_root, csv_path, tex_path, rijks_key, seen, dedupe, artist)
        except Exception as e:
            print("[warn] rijks failed:", e)

# === CLI ===
def main():
    ap = argparse.ArgumentParser(description="Fetch Open-Access images → local Art DB (UID + LaTeX index), sorted by artist last name.")
    # Smart mode
    ap.add_argument("--artist", type=str, default="", help="Ein-Kommando-Modus: Künstlername (z.B. 'Wassily Kandinsky')")
    ap.add_argument("--total-limit", type=int, default=400, help="Gesamtlimit (nur Smart-Modus)")
    ap.add_argument("--per-source-limit", type=int, default=300, help="Limit pro Quelle (nur Smart-Modus)")
    ap.add_argument("--sources", type=str, default="commons,europeana,met,cma,aic,rijks", help="Komma-Liste der Quellen im Smart-Modus")
    # Manual mode
    ap.add_argument("--source", choices=["met","aic","cma","rijks","commons","europeana"], help="Manuelle Quelle")
    ap.add_argument("--limit", type=int, default=50)
    ap.add_argument("--year-begin", type=int, default=1900)
    ap.add_argument("--year-end", type=int, default=2000)
    ap.add_argument("--query", type=str, default="")
    ap.add_argument("--images-root", type=str, default=None)
    ap.add_argument("--loose", action="store_true", help="(MET) weiter fassen, nicht nur Paintings (manuell)")
    ap.add_argument("--rijks-key", type=str, default=os.environ.get("RIJKS_API_KEY",""))
    ap.add_argument("--europeana-key", type=str, default=os.environ.get("EUROPEANA_API_KEY",""))
    ap.add_argument("--artist-filter", type=str, default="", help="nur Artists, deren Name diesen String enthält (manuell)")
    ap.add_argument("--no-dedupe", action="store_true", help="Dedupe deaktivieren (manuell)")
    args = ap.parse_args()

    images_root = resolve_images_root(args.images_root)
    art_dir = images_root / "Art"
    art_dir.mkdir(parents=True, exist_ok=True)
    csv_path = art_dir / "art_index.csv"
    tex_path = art_dir / "art_index.tex"
    ensure_index(csv_path)

    # Smart artist mode
    if args.artist:
        smart_fetch_artist(
            artist=args.artist,
            sources=[s.strip() for s in args.sources.split(",") if s.strip()],
            total_limit=args.total_limit,
            per_source_limit=args.per_source_limit,
            y0=args.year_begin, y1=args.year_end,
            art_dir=art_dir, images_root=images_root, csv_path=csv_path, tex_path=tex_path,
            rijks_key=args.rijks_key, europeana_key=args.europeana_key
        )
        print(f"\nOK ✓\nCSV: {csv_path}\nTEX: {tex_path}\nBilder unter: {art_dir}")
        return

    # Manual mode (backwards compatible)
    if not args.source:
        raise SystemExit("Bitte entweder --artist 'Name' ODER --source ... angeben.")
    seen = load_seen(csv_path); dedupe = not args.no_dedupe
    if args.source == "met":
        fetch_met(args.limit, args.year_begin, args.year_end, args.query, art_dir, images_root, csv_path, tex_path, args.loose, seen, dedupe, args.artist_filter)
    elif args.source == "aic":
        fetch_aic(args.limit, args.year_begin, args.year_end, args.query, art_dir, images_root, csv_path, tex_path, seen, dedupe, args.artist_filter)
    elif args.source == "cma":
        fetch_cma(args.limit, args.year_begin, args.year_end, args.query, art_dir, images_root, csv_path, tex_path, seen, dedupe, args.artist_filter)
    elif args.source == "rijks":
        fetch_rijks(args.limit, args.year_begin, args.year_end, args.query, art_dir, images_root, csv_path, tex_path, args.rijks_key, seen, dedupe, args.artist_filter)
    elif args.source == "commons":
        fetch_commons(args.limit, args.query, art_dir, images_root, csv_path, tex_path, seen, dedupe, args.artist_filter, force_artist=args.artist_filter or "")
    elif args.source == "europeana":
        fetch_europeana(args.limit, args.query, art_dir, images_root, csv_path, tex_path, args.europeana_key, seen, dedupe, args.artist_filter)

    print(f"\nOK ✓\nCSV: {csv_path}\nTEX: {tex_path}\nBilder unter: {art_dir}")

if __name__ == "__main__":
    main()
